### ISSUE TITLE
Add atributes to Exceptions in hva/core

### ISSUE THREAD

**Issue by inesiscosta** [inesiscosta/VetHotel#1]
Currently app uses e.getMessage() or other methods to get the unknown/duplicate ids etc. This info should be stored inside the exception instead.

**Comment by migpovrap** [comment]
Changed the exceptions to store the information on them be it the duplicated id or name, and added a method to get that id or name from the exception. This was done in the abstract exception UnknownIdException and DuplicateIdException. 
There is still a small thing that can be made better which is the way the EmployeeNotResponsibleException works for now it only stores the id of the responsibility but i think it should store also the id of the employee that is not responsible.
This is changed in the [commit](https://github.com/inesiscosta/VetHotel/commit/5402dcf4845d619d9a8f068e0a94ddfdf9c9de99)

**Comment by migpovrap** [comment]
Now the src/hva/core/exception/UnknownResponsibilityIdException.java and src/hva/core/exception/EmployeeNotResponsibleException.java store both the id of the employee and the id of responsibility in cause. Problem resolve.
